- name: Gather physical host facts
  setup:
    gather_subset: "network,virtual"
  delegate_to: "{{ physical_host }}"
  delegate_facts: true
  run_once: true

  # fixme: this should become a prepare physical_host play or something like that
- name: Install Dependencies
  delegate_to: "{{ physical_host }}"
  package:
    name: [ 'systemd-container', 'debootstrap']
  when: install_dependencies == true 

- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "{{ hostvars[physical_host]['ansible_distribution'] | lower }}-{{ hostvars[physical_host]['ansible_distribution_version'] | lower }}.yml"
      - "{{ hostvars[physical_host]['ansible_distribution'] | lower }}-{{ hostvars[physical_host]['ansible_distribution_major_version'] | lower }}.yml"
      - "{{ hostvars[physical_host]['ansible_os_family'] | lower }}-{{ hostvars[physical_host]['ansible_distribution_major_version'] | lower }}.yml"
      - "{{ hostvars[physical_host]['ansible_distribution'] | lower }}.yml"
      - "{{ hostvars[physical_host]['ansible_os_family'] | lower }}.yml"
      skip: true
  tags:
    - always

- name: Escape quote container name
  command: "systemd-escape {{ inventory_hostname }}"
  changed_when: false
  register: systemd_escape
  delegate_to: "{{ physical_host }}"
  tags:
    - skip_ansible_lint
    - always

- name: Get container status
  command: machinectl status "{{ inventory_hostname }}"
  register: machinectl_container_status
  failed_when: false
  changed_when: false
  delegate_to: "{{ physical_host }}"

- name: Get container image status
  command: machinectl image-status "{{ inventory_hostname }}"
  register: machinectl_container_image_status
  failed_when: false
  changed_when: false
  delegate_to: "{{ physical_host }}"

- name: Get base image status
  command: machinectl image-status "{{ container_image }}"
  register: machinectl_image_status
  failed_when: false
  changed_when: false
  delegate_to: "{{ physical_host }}"

- name: Fail if base image does not exist
  fail:
    msg: >
      The base container image "{{ container_image }}" does not exist. Check
      the name and try again.
  when:
    - machinectl_image_status.rc != 0

- name: Locate nspawn config
  stat:
    path: "/etc/systemd/nspawn/{{ inventory_hostname }}.nspawn"
  register: nspawn_config
  changed_when: false
  delegate_to: "{{ physical_host }}"

- name: Create nspawn directory
  file:
    path: "/etc/systemd/nspawn"
    state: "directory"
  delegate_to: "{{ physical_host }}"
  when:
    - not nspawn_config.stat.exists

- name: Create dropin config directory
  file:
    path: "/etc/systemd/{{ inventory_hostname }}.service.d"
    state: "directory"
  when: use_existing_netns is defined
  delegate_to: "{{ physical_host }}"

- name: Copy container config
  template:
    src: templates/container_config.nspawn.j2
    dest: "/etc/systemd/nspawn/{{ inventory_hostname }}.nspawn"
    owner: "root"
    group: "root"
    mode: "0644"
  register: container_config_new
  delegate_to: "{{ physical_host }}"
  when: not nspawn_config.stat.exists | bool

- name: Copy container service dropin config
  template:
    src: templates/systemd-netnamespace-dropin.conf.j2
    dest: "/etc/systemd/system/{{ inventory_hostname }}.service.d/use_existing_netns.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  delegate_to: "{{ physical_host }}"
  when: use_existing_netns is defined

- name: Clone the base container image
  command: machinectl clone "{{ container_image }}" "{{ inventory_hostname }}"
  register: machinectl_container_clone
  retries: 3
  delay: 2
  until: machinectl_container_clone is success
  delegate_to: "{{ physical_host }}"
  tags:
    - skip_ansible_lint
  when:
    - machinectl_container_image_status.rc != 0

- name: Create Container directories
  file:
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "/var/lib/machines/{{ inventory_hostname }}/var/log/journal"
    - "/var/lib/machines/{{ inventory_hostname }}/etc/systemd/network"
    - "/var/lib/machines/{{ inventory_hostname }}/var/lib/dbus"
  delegate_to: "{{ physical_host }}"
  when:
    - machinectl_container_image_status.rc == 0

- name: Container RO bind path cleanup
  file:
    path: "/var/lib/machines/{{ inventory_hostname }}/{{ item.container_path | default(item.host_path) }}"
    state: "absent"
  with_items: "{{ container_default_ro_bind_mounts | union(container_ro_bind_mounts | default([])) }}"
  delegate_to: "{{ physical_host }}"
  when:
    - machinectl_container_status.rc != 0

- name: Create Container inner directories
  file:
    path: "/var/lib/machines/{{ inventory_hostname }}/{{ item.container_path | default(item.host_path) }}"
    state: "directory"
  with_items: "{{ container_default_bind_mounts | union(container_bind_mounts | default([])) }}"
  delegate_to: "{{ physical_host }}"

- name: Container outer service directories
  file:
    path: "{{ item.host_path }}"
    state: "directory"
  with_items: "{{ container_default_bind_mounts | union(container_bind_mounts | default([])) }}"
  delegate_to: "{{ physical_host }}"

- name: Generate machine-id
  command: "systemd-machine-id-setup --root=/var/lib/machines/{{ inventory_hostname }}"
  args:
    creates: "/var/lib/machines/{{ inventory_hostname }}/etc/machine-id"
  register: machineid_set
  retries: 3
  delay: 2
  until: machineid_set is success
  delegate_to: "{{ physical_host }}"
  tags:
    - skip_ansible_lint

- name: Create dbus machine-id
  copy:
    src: "/var/lib/machines/{{ inventory_hostname }}/etc/machine-id"
    dest: "/var/lib/machines/{{ inventory_hostname }}/var/lib/dbus/machine-id"
    mode: "0444"
    remote_src: "yes"
  remote_user: root
  delegate_to: "{{ physical_host }}"

- name: Create systemd-network default config
  template:
    src: templates/systemd-networkd_default.network.j2
    dest: "/var/lib/machines/{{ inventory_hostname }}/etc/systemd/network/default.network"
    owner: "root"
    group: "root"
    mode: "0644"
  delegate_to: "{{ physical_host }}"
  # when: not host_netns

  # fixme: this should copy /etc/resolv.conf if resovled is not used
- name: Create resolved link
  file:
    src: "/var/run/systemd/resolve/resolv.conf"
    dest: "/var/lib/machines/{{ inventory_hostname }}/etc/resolv.conf"
    force: true
    follow: false
    state: link
  delegate_to: "{{ physical_host }}"
  when:
    - nspawn_container_enable_resolved | bool

- name: Add DNS default server
  lineinfile:
    path: "/var/lib/machines/{{ inventory_hostname }}/etc/systemd/resolved.conf"
    regexp: '^.*DNS=$'
    insertafter: '[Resolve]'
    line: "DNS={{ dns_servers | default('46.246.46.246') }}"
  delegate_to: "{{ physical_host }}"
  when:
    - dns_servers is defined

- name: Enable LLMNR
  lineinfile:
    path: "/var/lib/machines/{{ inventory_hostname }}/etc/systemd/resolved.conf"
    regexp: '^.*LLNMR=$'
    insertafter: '[Resolve]'
    line: "LLMNR=yes"
  delegate_to: "{{ physical_host }}"
  when:
    - enable_llmnr is defined

- name: Create avahi config in container
  template:
    src: templates/avahi-daemon.conf.j2
    dest: "/var/lib/machines/{{ inventory_hostname }}/etc/avahi/avahi-daemon.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  register: container_avahi_config
  delegate_to: "{{ physical_host }}"
  when: enable_avahi == true

- name: Create .ssh directory
  file:
    path: "/var/lib/machines/{{ inventory_hostname }}/root/.ssh"
    state: "directory"
  delegate_to: "{{ physical_host }}"
  when: deploy_sshkey is defined

- name: Copy authorized keys
  copy:
    content: "{{ deploy_sshkey }}"
    dest: "/var/lib/machines/{{ inventory_hostname }}/root/.ssh/authorized_keys"
    owner: root
    group: root
    mode: "0640"
    force: no
  delegate_to: "{{ physical_host }}"
  when: deploy_sshkey is defined

- name: Start new container (enable)
  systemd:
    daemon_reload: yes
    name: "systemd-nspawn@{{ inventory_hostname }}"
    state: "{{ ((machinectl_container_clone is changed or container_config_new is changed) | default(false)) | ternary('restarted', 'started') }}"
    enabled: true
  register: machinectl_start
  retries: 5
  delay: 2
  until: machinectl_start is success
  delegate_to: "{{ physical_host }}"

- name: Generate hostname
  command: >-
    hostnamectl --machine="{{ inventory_hostname }}" {{ item }} --pretty --static --transient
  with_items:
    - "set-hostname {{ inventory_hostname | replace('_', '-') }}.{{ physical_host }}.{{ container_domain }}"
    - "set-location {{ physical_host }}"
    - "set-chassis container"
    - "set-deployment {{ container_domain }}"
    - "set-icon-name container"
  register: hostnamectl_set
  retries: 3
  delay: 2
  until: hostnamectl_set is success
  delegate_to: "{{ physical_host }}"
  tags:
    - skip_ansible_lint

# This point the container is running. Delegation should no longer be required.
# ==============================================================================

- name: Force all notified handlers now
  meta: flush_handlers

- name: (RE)Gather facts post setup
  setup:
    #gather_subset: "network,hardware,virtual"
