---
- name: "install dependencies on pyhsical host"
  delegate_to: "{{ physical_host }}"
  package:
    name: [ 'systemd-container', 'debootstrap', 'libnss-mymachines' ]
  when: install_dependencies == true 
  # needs when and other distros
- name: "debootstrap ubuntu container"
  command: 'debootstrap --components=main,universe --arch=amd64 --include vim,openssh-server,avahi-daemon focal /var/lib/machines/ubuntu-focal-amd64 http://de.archive.ubuntu.com/ubuntu'
  args:
    creates: /var/lib/machines/ubuntu-focal-amd64
  delegate_to: "{{ physical_host }}"
  when: install_dependencies == true 
- service:
    name: systemd-networkd
    state: started
    enabled: yes
  delegate_to: "{{ physical_host }}"
- service:
    name: systemd-resolved
    state: started
    enabled: yes
  delegate_to: "{{ physical_host }}"
