---
- name: restart systemd-resolved
  service:
    name: systemd-resolved
    state: restarted
  failed_when: false
- name: restart systemd-networkd
  service:
    name: systemd-networkd
    state: restarted
  failed_when: false
- name: restart ssh
  service:
    name: ssh
    state: restarted
  failed_when: false
- name: restart avahi-daemon
  service:
    name: avahi-daemon
    state: restarted
  failed_when: false
