handlers:
  - name: restart systemd-resolved
    service:
      name: systemd-resolved
      state: restarted
  - name: restart systemd-networkd
    service:
      name: systemd-networkd
      state: restarted
