---
# This Playbook test if all defined containers can be reached via ansible
# Run nspawn-containers-create.yml before to create them 
- name: Test containers
  hosts: all_containers
  gather_facts: false
  become: true
  tasks:
    - name: Test connectivity to container gateway
      command: ping -c 1 10.0.4.1
      register: machinectl_ping
      retries: 3
      delay: 5
      until: machinectl_ping is success
      tags:
        - skip_ansible_lint

    - name: Test connectivity to internal address
      command: ping -c 1 172.29.100.101
      register: machinectl_ping
      retries: 3
      delay: 5
      until: machinectl_ping is success
      tags:
        - skip_ansible_lint

    - name: Test connectivity to container specific extra address
      command: ping -c 1 172.29.254.100
      register: machinectl_ping
      retries: 3
      delay: 5
      until: machinectl_ping is success
      tags:
        - skip_ansible_lint
