---
# this playbook setups the host machine. It creates an ssh keypair an drops
# an authorized_keys in /var/lib/machines it will later be mounted into the 
# container.
- name: Setup ssh key environment
  hosts: physical_host
  become: true
  tasks:
    - name: Gather facts
      setup:
        gather_subset: "!all"

    - name: Ensure user ssh key
      user:
        name: "{{ ansible_user_id | default('root') }}"
        generate_ssh_key: "yes"
        ssh_key_bits: 2048
        ssh_key_file: ".ssh/nspawn"

    - name: Get ssh key
      slurp:
        src: '~/.ssh/nspawn.pub'
      register: _ssh_key

    - name: Prepare container ssh key fact
      set_fact:
        user_ssh_key: "{{ _ssh_key['content'] | b64decode }}"

    - name: create an authorized_keys file to mount to containers
      file:
        path: '/var/lib/machines/.ssh'
        state: directory

    - name: create an authorized_keys file to mount to containers
      copy:
        content: "{{ user_ssh_key }}"
        mode: 0600
        dest: '/var/lib/machines/.ssh/authorized_keys'

    - name: install avahi
      package:
        name: avahi-daemon
        state: present
