---
# this playbook creates an ssh keypair an drops an authorized_keys in /var/lib/machines
# it will later be mounted into the container
- name: Setup ssh key environment
  hosts: physical_host
  connection: local
  become: false
  tasks:
    - name: Gather facts
      setup:
        gather_subset: "!all"

    - name: Show host facts
      debug:
        var: hostvars

    - name: Ensure user ssh key
      user:
        name: "{{ ansible_user_id | default('root') }}"
        generate_ssh_key: "yes"
        ssh_key_bits: 2048
        ssh_key_file: ".ssh/nspawn"

    - name: Get root ssh key
      slurp:
        src: '~/.ssh/nspawn.pub'
      register: _root_ssh_key

    - name: Prepare container ssh key fact
      set_fact:
        user_ssh_key: "{{ _root_ssh_key['content'] | b64decode }}"

    - name: create an authorized_keys file to mount to containers
      copy:
        content: "{{ user_ssh_key }}"
        dest: '/var/lib/machines/.ssh/authorized_keys'
