---
ansible_host: 172.29.100.102
ansible_become: True
ansible_user: root

physical_host: physical_testhost

container_networks:
  veth:
    address: "{{ ansible_host }}"
    netmask: "255.255.255.0"
    type: veth
