---
ansible_host: 172.29.100.103
ansible_become: True
ansible_user: root

physical_host: physical_host

container_networks:
  hostinterface:
    address: "1.3.3.7"
    netmask: "255.255.255.0"
    interface: test1
    type: hostinterface

