---
ansible_become: True
ansible_user: root

physical_host: physical_host

container_networks:
  veth:
    address: "{{ ansible_host }}"
    netmask: "255.255.255.0"
    type: veth
    ports:
      - protocol: tcp
        host_port: 80
        container_port: 8080
